### ISSUE TITLE
Decimal ranges create compilation errors

### ISSUE THREAD

**Issue by djonesz** [RicoSuter/NJsonSchema#1799]
My JSON schema has this property:
```json
"rate": {
  "type": "number",
  "format": "decimal",
  "maximum": 99999.99,
  "minimum": 0.0,
  "nullable": true
}
```

When generating a C# client, it creates this code:
```cs
[Newtonsoft.Json.JsonProperty("rate", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
[System.ComponentModel.DataAnnotations.Range(0.0M, 99999.99M)]
public decimal? Rate { get; set; } = default!;
```

This fails to compile because System.ComponentModel.DataAnnotations.Range can't take decimals (just doubles).

I believe this was mistakenly introduced in https://github.com/RicoSuter/NJsonSchema/pull/1720

Using version NJSonSchema v11.2.0, System.ComponentModel.DataAnnoations v5.0.0, .NET 9.0.

**Comment by djonesz** [comment]
Also see https://github.com/RicoSuter/NSwag/issues/5132
